#Confluence 
confluence.username: ''
confluence.password: ''
confluence.url: 'http://confluence.........:8090'
confluence.pageid: ''
################################################################################
#Credentials for ESXI
esxi.username : ''
esxi.password : ''
esxi.url: ''
################################################################################
#Credentials to cinnect by SSH
ssh.username: ''
ssh.password: ''
#Number of devices to connect in a Thread
limit: 20
#Domains of an Enterprise
#Networ Device's hostname consists of two parts - name and domain. These domaip parts will be filtered later in the script 
domains: 
    - ''
    - ''
    - ''
#For distinguishing device roles 
#Add some if needed, thats how device role will be assigned
switches:
    - 'WS-'
    - '9200'  
switches_L3:
    - 'WS-C3750'
    - 'WS-C3850'
    - '6807'
    - '9300'
    - 'N9K-C93240'
    - 'N9K-C93180'
    - 'N3K-C3172'
    - 'N5K-C5548'
    - 'N9K-C9508'
    - 'N3K-C3548'
#For distinguishing sites and region codes
# SITE: city code
sites:
    ELS: 78
    REN: 78
################################################################################
#Netbox
netbox.url: 'https://*.*.*.*'
netbox.token: ''
netbox.debug: ''
################################################################################
zabbix.url : 'http://*/'
zabbix.user : ''
zabbix.password : ''
debug: 0
# Edit roles according to your network. These roles are used to assign templates
processed_roles:
  - router
  - switch
  - switch_layer_3
  - switch_cod
  - wlc
  - ap

template:
    router:
        - Cisco Router
        - Template SNMP BGP
        - Template SNMP OSPF
    switch_layer_3:
        - Cisco Router
        - Template SNMP BGP
        - Template SNMP OSPF
    router_dzr:
        - Cisco Router
        - Template SNMP BGP
        - Template SNMP OSPF
    switch_cod:
        - Cisco Switch Datacenter
    switch:
        - Cisco Switch Office
    switch_smb_cod:
        - Cisco Switch SMB Datacenter
    wlc:
        - Cisco WLC
    ap:
        - Simple ICMP
#group: site: role - zabbix devices group
group:
  N6:
    router:
        - group name
    switch:
        - group name2
    switch_layer_3:
        - group name
  ELS:
    router:
        - group name5
    switch:
        - group name...
